services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ./docker/mariadb:/var/lib/mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - TZ=${TZ}
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./frontend:/vesp/frontend
      - ./www:/vesp/www
    ports:
      - ${NGINX_HOST}:${NGINX_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mariadb

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_XDEBUG=${PHP_XDEBUG:-0}
        - TZ=${TZ}
    volumes:
      - ./.env:/vesp/.env
      - ./core:/vesp/core
      - ./www:/vesp/www
      - ./upload:/vesp/upload
      - ./tmp:/vesp/tmp
    cap_add:
      - SYS_PTRACE
    depends_on:
      - mariadb
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    restart: unless-stopped
    working_dir: /vesp/core
    command: sh -c 'composer install --no-dev && composer db:migrate && php-fpm'

  node:
    image: node:${NODE_VERSION}
    volumes:
      - ./.env:/vesp/.env
      - ./frontend:/vesp/frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - TZ=${TZ}
    depends_on:
      - nginx
    network_mode: 'service:nginx'
    restart: unless-stopped
    working_dir: /vesp/frontend
    command: sh -c 'yarn && yarn build && yarn start'