export default {
  project: 'Vesp',
  greetings: {
    title: 'Welcome!',
    message: 'Select a menu item to get started',
  },
  actions: {
    files: 'Files',
    upload: 'Upload',
  },
  security: {
    username: 'Username',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    greetings: 'Hello!',
    goodbye: 'Bye, bye...',
    profile: 'Profile',
    success_update_message: 'Your profile has been updated successfully!',
  },
  models: {
    user: {
      title_one: 'User',
      title_many: 'Users',
      username: 'Username',
      fullname: 'Fullname',
      password: 'Password',
      email: 'Email',
      phone: 'Phone',
      gender: 'Gender',
      gender_select: 'Please select...',
      gender_1: 'Male',
      gender_2: 'Female',
      company: 'Company',
      address: 'Address',
      country: 'Country',
      city: 'City',
      zip: 'Post code',
      lang: 'Language',
      active: 'Active',
      blocked: 'Blocked',
      role: 'Role',
      file: 'Avatar',
      comment: 'Comment',
    },
    user_role: {
      title_one: 'User Role',
      title_many: 'Users Roles',
      title: 'Title',
      scope: 'Scope',
      add_scope: 'Add scopes',
    },
    category: {
      title_one: 'Category',
      title_many: 'Categories',
      title: 'Title',
      description: 'Description',
      alias: 'Alias',
      products: 'Products',
      active: 'Active',
    },
    product: {
      title_one: 'Product',
      title_many: 'Products',
      title: 'Title',
      description: 'Description',
      alias: 'Alias',
      sku: 'SKU',
      price: 'Price',
      category: 'Category',
      active: 'Active',
    },
    order: {
      title_one: 'Order',
      title_many: 'Orders',
      name: 'Customer',
      email: 'Email',
      post: 'Post',
      city: 'City',
      address: 'Address',
      paid: 'Paid',
      total: 'Total',
    },
  },
  errors: {
    security: {
      inactive: 'Your account is not active',
      wrong: 'Wrong username or password',
    },
    category: {
      alias_exists: 'This alias already exists, please specify another one',
    },
    product: {
      alias_exists: 'Another product in this category is already using this alias',
    },
  },
}
