export default {
  project: 'Vesp',
  greetings: {
    title: 'Welcome!',
    message: 'Select a menu item to get started',
  },
  actions: {
    files: 'Files',
    upload: 'Upload',
  },
  shop: {
    currency: '₽',
    weight: 'g.',
  },
  security: {
    username: 'Username',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    greetings: 'Hello!',
    goodbye: 'Bye, bye...',
    profile: 'Profile',
    success_update_message: 'Your profile has been updated successfully!',
  },
  models: {
    user: {
      title_one: 'User',
      title_many: 'Users',
      username: 'Username',
      fullname: 'Fullname',
      password: 'Password',
      email: 'Email',
      phone: 'Phone',
      gender: 'Gender',
      gender_select: 'Please select...',
      gender_1: 'Male',
      gender_2: 'Female',
      company: 'Company',
      address: 'Address',
      country: 'Country',
      city: 'City',
      zip: 'Post code',
      lang: 'Language',
      active: 'Active',
      blocked: 'Blocked',
      role: 'Role',
      file: 'Avatar',
      comment: 'Comment',
    },
    user_role: {
      title_one: 'User Role',
      title_many: 'Users Roles',
      title: 'Title',
      scope: 'Scope',
      add_scope: 'Add scopes',
    },
    category: {
      title_one: 'Category',
      title_many: 'Categories',
      title: 'Title',
      description: 'Description',
      alias: 'Alias',
      products: 'Products',
      file: 'Image',
      parent: 'Parent',
      active: 'Active',
    },
    product: {
      title_one: 'Product',
      title_many: 'Products',
      tab_main: 'Properties',
      tab_files: 'Gallery',
      tab_links: 'Links',
      tab_categories: 'Categories',
      file: 'Image',
      title: 'Title',
      subtitle: 'Subtitle',
      article: 'Article',
      category: 'Category',
      description: 'Description',
      content: 'Content',
      alias: 'Alias',
      price: 'Price',
      old_price: 'Old Price',
      weight: 'Weight',
      made_in: 'Made In',
      flags: 'Flags',
      flag_new: 'New',
      flag_popular: 'Popular',
      flag_favorite: 'Favorite',
      colors: 'Colors',
      variants: 'Variants',
      active: 'Active',
    },
    order: {
      title_one: 'Order',
      title_many: 'Orders',
      tab_main: 'Main',
      tab_products: 'Products',
      tab_address: 'Address',
      num: 'Number',
      address: 'Address',
      cart: 'Cart',
      user: 'Customer',
      discount: 'Discount',
      weight: 'Weight',
      products: 'Products',
      total: 'Total',
      created_at: 'Ordered At',
      comment: 'Comment',
    },
    order_product: {
      product: 'Product',
      amount: 'Amount',
      weight: 'Weight',
      price: 'Price',
      discount: 'Discount',
      total: 'Total',
    },
    user_address: {
      title_one: 'Address',
      title_many: 'Addresses',
      company: 'Company',
      receiver: 'Receiver',
      address: 'Address',
      zip: 'Zip',
      city: 'City',
      email: 'Email',
      phone: 'Phone',
    },
  },
  errors: {
    user: {
      no_username: 'Username is required',
      no_fullname: 'Fullname is required',
      no_email: 'Email is required',
      username_exists: 'This username is already exists',
      email_exists: 'This email is already exists',
      inactive: 'This account is not active',
      blocked: 'This account is blocked',
    },
    login: {
      wrong: 'Wrong username or password',
    },
    category: {
      alias_exists: 'This alias already exists, please specify another one',
    },
    product: {
      alias_exists: 'Another product in this category is already using this alias',
    },
  },
}
