export default {
  project: 'Vesp',
  greetings: {
    title: 'Добро пожаловать!',
    message: 'Выберите пункт меню для начала работы',
  },
  actions: {
    files: 'Файлы',
    upload: 'Загрузка',
  },
  shop: {
    currency: '₽',
    weight: 'гр.',
  },
  security: {
    username: 'Логин',
    password: 'Пароль',
    login: 'Вход',
    logout: 'Выход',
    greetings: 'Привет!',
    goodbye: 'Пока, пока...',
    profile: 'Профиль',
    success_update_message: 'Ваш профиль был успешно обновлён!',
  },
  models: {
    user: {
      title_one: 'Пользователь',
      title_many: 'Пользователи',
      username: 'Логин',
      fullname: 'Полное имя',
      password: 'Пароль',
      email: 'Email',
      phone: 'Телефон',
      gender: 'Пол',
      gender_select: 'Выберите из списка...',
      gender_1: 'Мужской',
      gender_2: 'Женский',
      company: 'Компания',
      address: 'Адрес',
      country: 'Страна',
      city: 'Город',
      zip: 'Почтовый индекс',
      lang: 'Язык',
      active: 'Активно',
      blocked: 'Заблокировано',
      role: 'Группа',
      file: 'Аватар',
      comment: 'Комментарий',
    },
    user_role: {
      title_one: 'Группа',
      title_many: 'Группы',
      title: 'Название',
      scope: 'Разрешения',
      add_scope: 'Добавить',
    },
    category: {
      title_one: 'Категория',
      title_many: 'Категории',
      title: 'Название',
      description: 'Описание',
      alias: 'Псевдоним',
      products: 'Товары',
      file: 'Изображение',
      parent: 'Родитель',
      active: 'Включено',
    },
    product: {
      title_one: 'Товар',
      title_many: 'Товары',
      tab_main: 'Свойства',
      tab_files: 'Галерея',
      tab_links: 'Связи',
      tab_categories: 'Категории',
      file: 'Картинка',
      title: 'Название',
      subtitle: 'Заголовок',
      article: 'Артикул',
      category: 'Категория',
      description: 'Описание',
      content: 'Содержимое',
      alias: 'Псевдоним',
      price: 'Цена',
      old_price: 'Старая цена',
      weight: 'Вес',
      made_in: 'Страна производитель',
      flags: 'Отметки',
      flag_new: 'Новый',
      flag_popular: 'Популярный',
      flag_favorite: 'Особенный',
      colors: 'Цвета',
      variants: 'Варианты',
      active: 'Включено',
    },
    order: {
      title_one: 'Заказ',
      title_many: 'Заказы',
      tab_main: 'Основное',
      tab_products: 'Товары',
      tab_address: 'Адрес',
      num: 'Номер',
      address: 'Адрес',
      cart: 'Корзина',
      user: 'Покупатель',
      discount: 'Скидка',
      weight: 'Вес',
      products: 'Товары',
      total: 'Стоимость',
      created_at: 'Заказано',
      comment: 'Комментарий',
    },
    order_product: {
      product: 'Товар',
      amount: 'Количество',
      weight: 'Вес',
      price: 'Цена',
      discount: 'Скидка',
      total: 'Итого',
    },
    user_address: {
      title_one: 'Адрес',
      title_many: 'Адреса',
      company: 'Компания',
      receiver: 'Получатель',
      address: 'Адрес',
      zip: 'Индекс',
      city: 'Город',
      email: 'Email',
      phone: 'Телефон',
    },
  },
  errors: {
    user: {
      no_username: 'Укажите имя пользователя',
      no_fullname: 'Укажите полное имя',
      no_email: 'Укажите email',
      username_exists: 'Имя пользователя уже занято',
      email_exists: 'Такой email уже используется',
      inactive: 'Учётная запись не была активирована',
      blocked: 'Учётная запись заблокирована',
    },
    login: {
      wrong: 'Неправильное имя или пароль',
    },
    category: {
      alias_exists: 'Такой псевдоним уже существует, укажите другой',
    },
    product: {
      alias_exists: 'Другой товар в этой категории уже использует такой псевдоним',
    },
    address: {
      no_receiver: 'Вы должны указать получателя',
      no_address: 'Укажите адрес',
      no_zip: 'Укажите почтовый индекс',
      no_city: 'Нужно указать город',
      no_phone: 'Вы забыли указать номер телефона',
      no_email: 'Email обязателен для заполнения',
      wrong_email: 'Указан неверный email',
    },
  },
}
