export default {
  project: 'Vesp',
  greetings: {
    title: 'Добро пожаловать!',
    message: 'Выберите пункт меню для начала работы',
  },
  actions: {
    files: 'Файлы',
    upload: 'Загрузка',
  },
  security: {
    username: 'Логин',
    password: 'Пароль',
    login: 'Вход',
    logout: 'Выход',
    greetings: 'Привет!',
    goodbye: 'Пока, пока...',
    profile: 'Профиль',
    success_update_message: 'Ваш профиль был успешно обновлён!',
  },
  models: {
    user: {
      title_one: 'Пользователь',
      title_many: 'Пользователи',
      username: 'Логин',
      fullname: 'Полное имя',
      password: 'Пароль',
      email: 'Email',
      phone: 'Телефон',
      gender: 'Пол',
      gender_select: 'Выберите из списка...',
      gender_1: 'Мужской',
      gender_2: 'Женский',
      company: 'Компания',
      address: 'Адрес',
      country: 'Страна',
      city: 'Город',
      zip: 'Почтовый индекс',
      lang: 'Язык',
      active: 'Активно',
      blocked: 'Заблокировано',
      role: 'Группа',
      file: 'Аватар',
      comment: 'Комментарий',
    },
    user_role: {
      title_one: 'Группа',
      title_many: 'Группы',
      title: 'Название',
      scope: 'Разрешения',
      add_scope: 'Добавить',
    },
    category: {
      title_one: 'Категория',
      title_many: 'Категории',
      title: 'Название',
      description: 'Описание',
      alias: 'Псевдоним',
      products: 'Товары',
      file: 'Изображение',
      parent: 'Родитель',
      active: 'Включено',
    },
    product: {
      title_one: 'Товар',
      title_many: 'Товары',
      title: 'Название',
      description: 'Описание',
      alias: 'Псевдоним',
      sku: 'Артикул',
      price: 'Цена',
      category: 'Категория',
      active: 'Включено',
    },
    order: {
      title_one: 'Заказ',
      title_many: 'Заказы',
      name: 'Имя покупателя',
      email: 'Email',
      post: 'Индекс',
      city: 'Город',
      address: 'Адрес',
      paid: 'Оплачено',
      total: 'Стоимость',
    },
  },
  errors: {
    security: {
      inactive: 'Ваш аккаунт неактивен',
      wrong: 'Неправильное имя или пароль',
    },
    category: {
      alias_exists: 'Такой псевдоним уже существует, укажите другой',
    },
    product: {
      alias_exists: 'Другой товар в этой категори уже использует такой псевдоним',
    },
  },
}
